# Summary of Data Inputs

## Overview

This chapter describes all of the data inputs that are used in the model. All data inputs fall into one of the following categories: diet, health, environment, economic, social, and other.

In the "methods_manual" folder, there is a "data_inputs" subfolder that contains the following subfolders that correspond with each data input:

**Diet:**

- methods_manual/data_inputs/DIET/counterfactual_intake ([Box](https://tufts.box.com/s/2zhv1ugq6o0cd0ivts9cctyqto3or0du))
- methods_manual/data_inputs/DIET/dietary_intake ([Box](https://tufts.box.com/s/o8btvxrqaqskx8vztfecrr5tou2c1d6k))

**Economic:**

- methods_manual/data_inputs/ECONOMIC/fah_fafh_ratio
- methods_manual/data_inputs/ECONOMIC/food_prices

**Environment:**

- methods_manual/data_inputs/ENVIRONMENT/ghg_ced_impacts
- methods_manual/data_inputs/ENVIRONMENT/land_use
- methods_manual/data_inputs/ENVIRONMENT/water_impacts

**Health:**

- methods_manual/data_inputs/HEALTH/cancer_incidence
- methods_manual/data_inputs/HEALTH/cvd_mortality
- methods_manual/data_inputs/HEALTH/effect_sizes_dietfactor_bmi
- methods_manual/data_inputs/HEALTH/effect_sizes_dietfactor_sbp
- methods_manual/data_inputs/HEALTH/logrr_dietfactor_disease
- methods_manual/data_inputs/HEALTH/overweight_prevalence
- methods_manual/data_inputs/HEALTH/rr_bmi_cancer
- methods_manual/data_inputs/HEALTH/rr_bmi_cvd
- methods_manual/data_inputs/HEALTH/rr_sbp_cvd
- methods_manual/data_inputs/HEALTH/systolic_blood_pressure
- methods_manual/data_inputs/HEALTH/tmred

**Social:**

- methods_manual/data_inputs/SOCIAL/forced_labor

**Other:**

- methods_manual/data_inputs/OTHER/dietfactor_to_fcid_mapping
- methods_manual/data_inputs/OTHER/dietfactor_to_fndds_mapping
- methods_manual/data_inputs/OTHER/food_waste
- methods_manual/data_inputs/OTHER/labels
- methods_manual/data_inputs/OTHER/unit_conversions
- methods_manual/data_inputs/OTHER/us_population

\newpage

## Diet Inputs

### Counterfactual Intake

#### Purpose {-}

This dataset contains three recommended dietary patterns (Healthy U.S.-Style Dietary Pattern, Healthy Vegetarian Dietary Pattern, and Healthy Mediterranean-Style Dietary Pattern) from the Dietary Guidelines for Americans (DGA) 2020-2025 report; 1 vegan dietary pattern published in the literature, and 1 dietary pattern that was constructed by the LASTING team (DGA+ Pattern). This dataset serves as the “ideal” dietary pattern that we are shifting to in the 4 models.

#### Raw data sources {-}

- DGA 2020-2025, Table A3-2: Healthy U.S.-Style Dietary Pattern for Ages 2 and Older ([data](https://www.dietaryguidelines.gov/sites/default/files/2020-12/Dietary_Guidelines_for_Americans_2020-2025.pdf))
- DGA 2020-2025, Table A3-4: Healthy Vegetarian Dietary Pattern for Ages 2 and Older ([data](https://www.dietaryguidelines.gov/sites/default/files/2020-12/Dietary_Guidelines_for_Americans_2020-2025.pdf))
- DGA 2020-2025, Table A3-5: Healthy Mediterranean-Style Dietary Pattern for Ages 2 and Older ([data](https://www.dietaryguidelines.gov/sites/default/files/2020-12/Dietary_Guidelines_for_Americans_2020-2025.pdf))
- Vegan dietary pattern: Hess 2022 ([paper](https://doi.org/10.1093/jn/nxac100))
- DGA+ pattern: AHA recs, ACS recs (Brooke - add more info here)

#### Raw data location {-}

- methods_manual/data_inputs/DIET/counterfactual_intake/RESOURCES/DGA 2020-2025/Table A3-2 Healthy U.S.-Style.xlsx
- methods_manual/data_inputs/DIET/counterfactual_intake/RESOURCES/DGA 2020-2025/Table A3-4 Healthy Vegetarian.xlsx
- methods_manual/data_inputs/DIET/counterfactual_intake/RESOURCES/DGA 2020-2025/Table A3-5 Healthy Mediterranean-Style.xlsx
- methods_manual/data_inputs/DIET/counterfactual_intake/RESOURCES/Vegan/Hess 2022.pdf
- methods_manual/data_inputs/DIET/counterfactual_intake/RESOURCES/DGA+/Org dietary recommendations - operationalized.xlsx

#### Data pre-processing notes {-}

We use the 2,000-calorie recommendations for all dietary patterns.

Standard deviations were calculated as 10% of the recommendation value, and standard errors were set to 0.

Any recommendation values at the week-level were converted to day-level. For example, the Healthy U.S.-Style recommends 1.5 cups/week of dark-green vegetables. This value was divided by 7 and the new value is 0.21 cups/day.

Some of the DGA recommendations for various food items were grouped together. For example, the Healthy U.S.-Style recommends 26 oz/week of meats, poultry, and eggs, but it does not provide values for just meats, poultry, or eggs. Therefore, to get recommendation values for each of these three food items individually, we used NHANES 2015-2018 data to look at the intake distribution of these three food items and then applied that proportion to the total 26 oz/week value. This same method was applied to the food group ‘Nuts, seeds, and soy products’, and ‘Limit on calories for other uses’ (added sugar and saturated fat).

We also had to construct recommendation values for the dietary factors ‘fruit_exc_juice’ (fruit excluding juice) and ‘veg_exc_sta’ (vegetables excluding starchy vegetables).

The recommendation value for veg_exc_sta was simply the sum of the recommendation values for veg_dg (dark-green vegetables), veg_ro (red-orange vegetables), and veg_oth (other vegetables).

To calculate the recommendation value for fruit_exc_juice, we utilized the proportion of whole fruits to fruit juice from NHANES. Approximately 75% of total fruit consumed was whole fruit excluding juice. Therefore, the recommendation value for fruit_exc_juice was the DGA recommended value for total fruit multiplied by 0.753.

The NHANES proportions are located in:

- methods_manual/data_inputs/DIET/counterfactual_intake/DATA/NHANES proportions.xlsx (sheets ‘Fruit proportions’, ‘Veg proportions’, ‘Animal protein props US MED’, ‘Veg protein proportions US MED’, and ‘Sugar proportions’)

#### Raw data (pre-processed) location {-}

- methods_manual/data_inputs/DIET/counterfactual_intake/DATA/counterfactual_intake_050724.csv

\newpage

### Dietary Intake

#### Purpose {-}

This dataset contains an estimate of the U.S. population-level average daily intake, stratified by food subgroup, age group, and sex.

#### Raw data sources {-}

- National Health and Nutrition Examination Survey (NHANES), 2015-2016 cycle ([data](https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?BeginYear=2015))
- National Health and Nutrition Examination Survey (NHANES), 2017-2018 cycle ([data](https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?BeginYear=2017))
- Food Patterns Equivalents Database per 100 grams of FNDDS 2015-2016 foods ([data](https://www.ars.usda.gov/northeast-area/beltsville-md-bhnrc/beltsville-human-nutrition-research-center/food-surveys-research-group/docs/fped-databases/))
- Food Patterns Equivalents Database per 100 grams of FNDDS 2017-2018 foods ([data](https://www.ars.usda.gov/northeast-area/beltsville-md-bhnrc/beltsville-human-nutrition-research-center/food-surveys-research-group/docs/fped-databases/))
- Food Patterns equivalents for foods in the WWEIA, NHANES 2015-2016 ([data](https://www.ars.usda.gov/northeast-area/beltsville-md-bhnrc/beltsville-human-nutrition-research-center/food-surveys-research-group/docs/fped-databases/))
- Food Patterns equivalents for foods in the WWEIA, NHANES 2017-2018 ([data](https://www.ars.usda.gov/northeast-area/beltsville-md-bhnrc/beltsville-human-nutrition-research-center/food-surveys-research-group/docs/fped-databases/))
- WWEIA Food Categories, 2015-2016 ([data](https://www.ars.usda.gov/ARSUserFiles/80400530/apps/WWEIA1516_foodcat_FNDDS.xlsx))
- WWEIA Food Categories, 2017-2018 ([data](https://www.ars.usda.gov/ARSUserFiles/80400530/apps/WWEIA1718_foodcat_FNDDS.xlsx))

#### Raw data location {-}

- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/dr1iff_i.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/dr2iff_i.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/dr1iff_j.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/dr2iff_j.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/fped_dr1iff_1516.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/fped_dr2iff_1516.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/fped_dr1iff_1718.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/fped_dr2iff_1718.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/demo_i.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/demo_j.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/fped_dr1tot_1516.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/fped_dr2tot_1516.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/fped_dr1tot_1718.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/dr1tot_i.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/dr2tot_i.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/dr1tot_j.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/dr2tot_j.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/WWEIA1516_foodcat_FNDDS.xlsx
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/WWEIA1718_foodcat_FNDDS.xlsx
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/fped_1516.sas7bdat
- methods_manual/data_inputs/DIET/dietary_intake/DATA/raw_data/fped_1718.sas7bdat

#### Data pre-processing notes {-}

We estimated the average intake of the following food groups:

Vegetables:

1. Dark-green vegetables (“veg_dg”): Dark green vegetables (cup eq.)
2. Red and orange vegetables (“veg_ro”): Other red and orange vegetables, excluding tomatoes and tomato products (cup eq.)
3. Starchy vegetables (“veg_sta”): Total starchy vegetables (white potatoes and other starchy vegetables) (cup eq.)
4. Other vegetables (“veg_oth”): Other vegetables not in the vegetable components listed above (cup eq.)
5. Vegetables, excluding starchy (“veg_exc_sta”): dark green vegetables; other red and orange vegetables, excluding tomatoes and tomato products; and other vegetables not in the vegetable components listed above (cup eq.)

Fruit:

6. Total fruit (“fruit_tot”): Total intact fruits (whole or cut) and fruit juices (cup eq.)
7. Whole fruit, excluding juice (“fruit_exc_juice”): Intact fruits (whole or cut) of citrus, melons, and berries; and intact fruits (whole or cut) excluding citrus, melons, and berries (cup eq.)
8. Fruit juice, 100% (“fruit_juice”): Fruit juices, citrus and non-citrus (cup eq.)

Grains:

9. Whole grains: Grains defined as whole grains and contain the entire grain kernel ― the bran, germ, and endosperm (oz. eq.)
10. Refined grains: Refined grains that do not contain all of the components of the entire grain kernel (oz. eq.)

Dairy:

11. Total dairy: Total milk, yogurt, cheese, and whey; and calcium-fortified soy milk (cup ep.)
12. Animal-based dairy (“dairy_cow”): Milk, yogurt, cheese, and whey (cup ep.)
13. Soy-based dairy (“dairy_soy”): Calcium fortified soy milk (soymilk) (cup ep.)

Animal-sourced protein:

14. Eggs: Eggs (chicken, duck, goose, quail) and egg substitutes (oz. eq.)
15. Seafood: Seafood (finfish, shellfish, and other seafood) high in n-3 fatty acids; and seafood (finfish, shellfish, and other seafood) low in n-3 fatty acids (oz. eq.)
16. Unprocessed poultry (“pf_poultry”): Chicken, turkey, Cornish hens, duck, goose, quail, and pheasant (game birds) (oz. eq.)
17. Unprocessed and processed poultry (“pf_poultry_tot”): Chicken, turkey, Cornish hens, duck, goose, quail, and pheasant (game birds) (unprocessed poultry); and frankfurters, sausages, corned beef, cured ham and luncheon meat that are made from poultry (processed poultry) (oz. eq.)
18. Unprocessed red meat (“pf_redm”): Beef, veal, pork, lamb, and game meat (oz. eq.)
19. Unprocessed and processed red meat (“pf_redm_tot”): Beef, veal, pork, lamb, and game meat (unprocessed red meat); and frankfurters, sausages, corned beef, cured ham and luncheon meat that are made from beef or pork (processed red meat) (oz. eq.)
20. Processed red meat and poultry (“pf_pm”): Frankfurters, sausages, corned beef, cured ham and luncheon meat that are made from beef, pork, or poultry (oz. eq.)

Plant-sourced protein:

21. Nuts and seeds (“pf_ns”): Peanuts, tree nuts, and seeds; excludes coconut (oz. eq.)
22. Total legumes (“leg_tot”): Beans, peas, and lentils; and soy products, excluding calciumfortified soy milk and raw soybean products (oz. eq.)
23. Unsaturated fat (oil) (“oil”): Fats naturally present in nuts, seeds, and seafood; all unhydrogenated vegetable oils, except palm oil, palm kernel oil, and coconut oils; the fat present in avocado and olives above the allowable amount; and 50% of the fat present in stick and tub margarines and margarine spreads (g)

Added fat and sugar:

24. Saturated fats (“sat_fat”): Total saturated fatty acids; includes saturated fat from animal foods and some plant foods, including coconut, coconut oil, palm oil, and palm kernel oil (g)
25. Added sugar (“added_sugar”): Foods defined as added sugars; includes sugars (free, mono-, and disaccharides), sugars from syrups and honey, and sugars from concentrated fruit or vegetable juices that are in excess of what would be expected from the same volume of 100% fruit or vegetable juices of the same type (tsp. eq.)
26. Sugar-sweetened beverages (“ssb”): Beverages containing 5 or more grams of added sugar

##### Sugar-sweetened beverages {-}

Since the FPED dataset does not report intake of sugar-sweetened beverages (SSB), we constructed our own SSB variable. If any reported food item in the NHANES dataset was assigned the WWEIA category code 151=Sugar-sweetened beverages, 152=Sugar-sweetened beverages (diet vs. SSB), 153=Nutritional beverages (diet vs. SSB), 154=Smoothies and grain drinks (diet vs. SSB), 155=Coffee, or 156=Tea AND contained 5 or more grams of added sugar, then it was considered an SSB.

##### Processed meat {-}

Because the environmental impact factors don’t take “processed” into consideration, we needed to create two new food subgroups to use in the environment analysis: “total red meat” and “total poultry”, which include both unprocessed and processed meats. We disaggregated the "processed meat” category into “processed red meat” and “processed poultry” categories using SAS macros developed by the USDA1. Then, we summed the intake amounts of unprocessed red meat and processed red meat to obtain “total red meat”; and summed the intake amounts of unprocessed poultry and processed poultry to obtain “total poultry”.

##### Legumes {-}

The Dietary Guidelines provides two separate intake recommendations for “Beans, Peas, and Lentils” for the Vegetarian dietary pattern: 0.21 cups/day (as part of the vegetables food group) and 0.21 cups/day (as part of the protein food group), resulting in a total of 0.42 cups/day. Ultimately, beans/legumes as vegetables and beans/legumes as protein are the same food item, and thus the CRA cannot model these separately. Therefore, we decided to treat legumes as one food subgroup. We summed the intake amounts of beans, peas, lentils, and soy products, excluding calcium-fortified soy milk and raw soybean products to obtain “total legumes”. Note that this category does not include peanuts.

##### Standard deviations

The SIMPLE macro was adapted to additionally estimate the standard deviations of intake means. See more info in Chapter \@ref(sas-macro).

#### Raw data (pre-processed) location {-}

- methods_manual/data_inputs/DIET/dietary_intake/DATA/output_data_from_cluster/NHANES_1518_summary_allfoods_adj_bysub_ncimethod_2025-05-20.csv

\newpage

## Economic Inputs

### Food Cost {#food-cost}

\newpage

### Food-At-Home (FAH) vs. Food-Away-From-Home (FAFH) Ratio

\newpage

## Environment Inputs

### Greenhouse Gas Emissions (GHG) and Cumulative Energy Demand (CED) Impact Factors

\newpage

### Water Scarcity (WS) and Bluewater Use (BWU) Impact Factors

\newpage

## Health Inputs

### Cancer Incidence

#### Purpose {-}

This dataset contains U.S. disease-specific cancer incidence rates from 2018, by age, sex, and race/ethnicity.

The following cancers were included in the analysis:

- Colon and rectum (CC)
- Corpus uteri (UC)
- Esophagus: adenomas and adenocarcinomas (ECA) (Note: this is a subset of esophagus cancer)
- Female breast (post-menopause) (BC)*
- Gallbladder (GC)
- Kidney and renal pelvis (KC)
- Liver and intrahepatic bile duct (LVC)
- Lung and bronchus (LC)
- Meningiomas: meningiomas (MC)
- Myeloma: Multiple myeloma/plasma-cell leukemia (MMC)
- Mouth, larynx, and pharynx cancers (MLPC)
- Ovary (OC)
- Pancreas (PC)
- Prostate (advanced) (APCA) (Note: this is a subset of prostate cancer)
- Stomach cardia (SCC)
- Stomach non-cardia (SCNC)
- Thyroid (TC)

*We only included breast cancer cases from women who were diagnosed at ages 51 years or older to estimate the number of post-menopausal breast cancer cases.

#### Raw Data Sources {-}

- NCI Surveillance, Epidemiology, and End Results (SEER) Database, 2018 Cancer Incidence [data]

#### Raw Data Location {-}

- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/txt/cancerrate2018_0213.txt
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/txt/esophagus2018_0213.txt
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/txt/multiplemyeloma2018_0213.txt
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/txt/prostate2018_0213.txt
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/txt/stomach2018_0213.txt
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/txt/postmenopausal2018_1115.txt

#### Raw Data Processing Notes {-}

The following SAS codes were used to transform the raw .txt files into SAS datasets:

- methods_manual/data_inputs/HEALTH/cancer_incidence/CODE/cancerrate_wide2018_0213.sas
- methods_manual/data_inputs/HEALTH/cancer_incidence/CODE/esophagus2018_0213.sas
- methods_manual/data_inputs/HEALTH/cancer_incidence/CODE/multiplemyeloma2018_0213.sas
- methods_manual/data_inputs/HEALTH/cancer_incidence/CODE/prostate2018_0213.sas
- methods_manual/data_inputs/HEALTH/cancer_incidence/CODE/stomach2018_0213.sas
- methods_manual/data_inputs/HEALTH/cancer_incidence/CODE/postmenopausal2018_1115.sas

The resulting SAS dataset files are located here:

- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/cancerrate2018.sas7bdat
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/cancer.sas7bdat
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/esophagus.sas7bdat
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/myeloma.sas7bdat
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/prostate.sas7bdat
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/stomach.sas7bdat
- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/raw_data/postbreast.sas7bdat

Then, the following two SAS codes were used to calculate the estimated number of cancer cases per demographic subgroup in 2018:

- data_final/in/HEALTH PILLAR/Cancer incidence/Cancerrate2018CRUDE_1115.sas
- data_final/in/HEALTH PILLAR/Cancer incidence/cancerNHANES 1718POP_0212.sas (generates subgroup population number from NHANES)

First, the crude rate for each cancer for each demographic subgroup is calculated by dividing the number of cancer cases reported by the sample population size:

$$ Crude rate = count of cancer cases / sample population size $$

Then, this rate is applied to the 2018 subgroup population numbers (from the US Census Bureau—described in previous section):

$$ No. of cases = crude rate * population size $$

The number of post-menopausal breast cancer cases was calculated slightly differently than the others because we only wanted to estimate breast cancer cases from women who were diagnosed at ages 51 years or older. Specifically, for the demographic subgroups that were female and aged 45-54 (subgroups 17, 18, 19, 20), we applied the crude rate to the U.S. population size of those aged 51-54 (rather than aged 45-54).

#### Processed Raw Data Location {-}

The resulting processed dataset is located here:

- methods_manual/data_inputs/HEALTH/cancer_incidence/DATA/2018CANCERRATE_0327.xls

#### Cleaning Code Location {-}

The cleaning codes for this data input are located in Chapter 3.1.2 - Health Data Inputs [link] and Chapter 3.2.1 (1) Cancer incidence and (2) CVD mortality [link].

#### Data Cleaning Notes {-}

The standard error of the cancer counts is calculated as:

$$count_se = (crude_se / 100000) * population)$$

Also, the cancer and CMD datasets are merged into one combined "disease" dataset.

#### Clean Data Location {-}

The final cleaned dataset is located here:

- methods_manual/data_inputs/FINAL/cleaned_data/disease_incidence_YYYY-MM-DD_FINAL.csv

where "YYYY-MM-DD" is the most recent export date.

\newpage

### Cardiometabolic Disease (CMD) Mortality

\newpage

### Effect Sizes for Diet and Body Mass Index (BMI)

\newpage

### Effect Sizes for Diet and Systolic Blood Pressure (SBP)

\newpage

### Log Relative Risks (LogRR) for Diet-Cancer

\newpage

### Overweight Prevalence

\newpage

### Relative Risks (RR) for BMI and Cancer

\newpage

### Relative Risks (RR) for BMI and CMD

\newpage

### Relative Risks (RR) for SBP and CMD

\newpage

### Systolic Blood Pressure

\newpage

### TMRED

\newpage




## Social Inputs

### Forced Labor Risk

\newpage

## Other Inputs

### Mapping from Food Group to FCID Code

\newpage

### Mapping from Food Group to FNDDS Code {#mapping-from-food-group-to-fndds-code}

\newpage

### Inedible and Wasted Food Proportions

\newpage

### Labels

\newpage

### Weight Conversion Units

\newpage

### U.S. Population Size








