---
title: "LASTING Four-Pillar Model Methodology"
author: "Brooke M. Bell"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
# url: your book url like https://bookdown.org/yihui/bookdown
description: This is the comprehensive manual that describes all data inputs and methods used for the 4-pillar LASTING model.
link-citations: yes
# github-repo: rstudio/bookdown-demo
---

# Introduction {.unnumbered}

This is the comprehensive manual that describes all data inputs and methods used for the LASTING 4-pillar model.

This manual was built using **bookdown**, an open-source R package that facilitates writing books and long-form articles/reports with R Markdown.

## Github Repository {.unnumbered}

A Github repository (AKA repo) titled [methods_manual](https://github.com/brookembell/methods_manual) has been created to store all of the project's code, data, and documentation (including this manual). In order to gain access to the Github repo, you must ask Brooke to add you as a user.

## Data Inputs {.unnumbered}

All of the raw data inputs and cleaned datasets are located in the repo:

-   GitHub/methods-manual/data_inputs

The raw input files are located in their respectively named folders.

For example, the raw NHANES intake data is located in:

-   GitHub/methods-manual/data_inputs/DIET/dietary_intake/DATA/raw_data

The raw DataField GHG impact factor dataset is located in:

-   GitHub/methods-manual/data_inputs/ENVIRONMENT/ghg_ced_impacts/DATA

## Code {.unnumbered}

All of the data cleaning code is embedded within this manual.

All of the model code is located in a different repo titled [LASTING](https://github.com/fcudhea/LASTING), managed by Fred Cudhea. The goal is to eventually incorporate the model code into this manual as well, but it's still TBD.

Currently, only Fred Cudhea and Brooke Bell have access to this code. To gain access, please contact Fred and Brooke.

As of right now, the R code used to run the analysis on the Tufts High Performance Computing (HPC) Cluster is located in:

-   Github/LASTING/Code/cluster code

In order to gain access to the cluster, you must first request an account through ITS [here](https://it.tufts.edu/high-performance-computing).

The primary script is “LASTING_cluster_w_masterinput.R”. This script should be run on the cluster. For more details on how to run the code from the cluster, contact Fred and Brooke.

## Model Output {.unnumbered}

Output from the models is located in the Box folder here:

-   Box/lasting_aim_3/model_development/model_output

